### ISSUE TITLE
Just thinking :)

### ISSUE THREAD

**Issue by wmdhosting** [nystudio107/craft-code-field#1]
There is plugin 
Template selector.  
https://plugins.craftcms.com/template-selector?craft4

is there any way to load like that template..  in Code field... 
So we can edit template directly from craft..

**Comment by khalwat** [comment]
Yes, it would be doable... but it's not something I have planned for Code Field.

If someone else wants to do it based on Code Field, they are welcome to tho!

**Comment by michaelrog** [comment]
For the love of god, please don't.

**Comment by wmdhosting** [comment]
just asked question :) if its posiblle  :)

**Comment by khalwat** [comment]
It's definitely possible... wouldn't even be too much work tbh!
