### ISSUE TITLE
Can't access geojson code - error unknown property in migration preparation

### ISSUE THREAD

**Issue by alanski66** [nystudio107/craft-code-field#11]
### Describe the bug
Storing geoJSON code like screenshot attached.

Am changing/migrating  existing field by changing the field type for the entry to use the code field as per docs.
I'm setting json or plain text - issue is consistently the same. Produces an error when trying to access.

It is fine for creating a new entry and adding the geoJSON data - it just doesn't like opening existing data.

### To reproduce
Steps to reproduce the behaviour:
1. Open entry using code field that holds existing geoJSON data
2. Get the error
`Setting unknown property: nystudio107\codefield\models\CodeData::type`

### Expected behaviour
Open entry and display code 

### Versions
- Plugin version: 3.0.10
- Craft version: 3.8.16

![Geojson](https://github.com/nystudio107/craft-code-field/assets/1781739/7e16bf53-8025-4f17-a3ec-712a40fe084d)

**Comment by alanski66** [comment]
Seems the issue is in the normalizeValue (src/field/code.php)

MY json data is valid but this code:
` if (\is_string($value)) {
                $jsonValue = Json::decodeIfJson($value);
                // If this is still a string (meaning it's not valid JSON), treat it as the value
                if (\is_string($jsonValue)) {
                    $config['value'] = $jsonValue;
                } else {
                    $value = $jsonValue;
                }
            }`
seems to not test the truthfulness of its JSON validity.
My quick solution was to just do:

`//$jsonValue = Json::decodeIfJson($value);`
 
 `$jsonValue = $value;`
  
pants for other code types i imagine but not sure what validity check for php should be with difference's in native php versions - ie I think 8.3 will have json_validate natively.

**Comment by alanski66** [comment]
FYI: After successful migration to Craft 4 I start getting this error

`Declaration of nystudio107\codefield\fields\Code::normalizeValue($value, ?craft\base\ElementInterface $element = null) must be compatible with craft\base\Field::normalizeValue(mixed $value, ?craft\base\ElementInterface $element = null): mixed`
Reinstalled plugin: dev-develop-v4 9a51d39 => 4.0.9)
Hack above works :)

**Comment by khalwat** [comment]
Okay I think I see what's going on here... since the field data is in JSON, it tries to decode it as JSON, and create a model based on that.

**Comment by khalwat** [comment]
Regarding your second issue of the incorrect function declaration... what version of PHP is this?

Also are you saying that re-installing the plugin somehow fixed it?

**Comment by khalwat** [comment]
Okay I pushed a fix for both. If you could try them out, I'd appreciate it:

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-code-field": "dev-develop as 3.0.10”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-code-field": "dev-develop-v4 as 4.0.10”,
```
Then do a `composer clear-cache && composer update`

**Comment by alanski66** [comment]
This is way beyond my expectations of response so thank you!
Have only had time to look at Craft 4 migration and it seems to work perfectly. Previously I was getting unhelpful default values when i wanted the field empty.
I was accessing the data in the code field in my plugin via the file handle eg $element->geojson
However the data appears to now be in $element->geojson->value - is this correct /expected?

**Comment by khalwat** [comment]
Yes, it is expected that you access it via `$element->geojson->value` -- however, `$element->geojson` should work too, because it implements `__toString()` on the object:

https://github.com/nystudio107/craft-code-field/blob/develop-v4/src/models/CodeData.php#L42

Thanks for verifying, it's the same code in the Craft 3 version, so I'll cut a release.

**Comment by alanski66** [comment]
I know this is closed but just following up on the Craft 3 version.
I couldnt get composer to install:
`   - Root composer.json requires nystudio107/craft-code-field dev-develop as 3.0.10, found nystudio107/craft-code-field[dev-develop-v3, dev-develop-v4, 3.0.0, ..., v3.x-dev, 4.0.0, ..., v4.x-dev] but it does not match the constraint.
`

**Comment by khalwat** [comment]
You can just use the tagged release:

https://github.com/nystudio107/craft-code-field/releases/tag/3.0.10

```
    "nystudio107/craft-code-field": "^3.0.10”,
```
