### ISSUE TITLE
Syntax Highlighting only loading intermittently

### ISSUE THREAD

**Issue by MSchak** [nystudio107/craft-code-field#13]
### Describe the bug
Intermittent loading of syntax highlighting on the code editor. It seems like possibly the JS was loading at the wrong time or something else was conflicting. 

### To reproduce
Unsure, Followed the steps in the docs, editor shows on Front-end, but upon refreshing syntax highlighting will only show sometimes. 

### Expected behavior
Syntax highlighting works every time

### Versions
- Plugin version: 4.0
- Craft version: 4.5.11.1

### Resolution
Within a duped includeJS twig macro, we loaded the Monaco Js via `js on ready`, ideally this would be the default, or if there was a way to make it optional that would be great.

```
    {% js on ready %}
        makeMonacoEditor("{{ (fieldId)|namespaceInputId }}", "{{ fieldType }}", '{{ monacoOptions | json_encode | e('js') }}', '{{ codeEditorOptions | json_encode | e('js') }}', "{{ alias('@codeEditorEndpointUrl') }}");
    {% endjs %}
```

**Comment by khalwat** [comment]
Can you show me any console errors or something else to go on?

**Comment by MSchak** [comment]
Hello,

Thanks for responding! There are no console errors to speak of, although
I’m sending a screenshot of the page elements when it is loading vs. not.
There is no difference between the two pages besides a refresh. Sometimes
it works, sometimes not.

I can see that the script has loaded whether or not the highlighting is
showing. It seemed likely that the issue was the script firing before the
elements were loading, and the temporary fix we mentioned in the bug report
resolved the issue for us.


Hope this helps,
Megan S.

**Comment by khalwat** [comment]
Right but the way that script works is that it registers the asset bundle first, which should then include the script, and then it registers the JavaScript code that depends on the code in the asset bundle next. So it should solve the dependency issue.

If you view the source of the page, search on `makeMonacoEditor` and see if the script tags for the various JS that it needs appear before that code?

**Comment by MSchak** [comment]
The code-editor.js appears directly above the makeMonacoEditor script.

**Comment by khalwat** [comment]
That should cause things to load in the appropriate order. I'm unable to replicate what you're seeing locally here.

Are you able to make some kind of a minimal reproduction example I can follow? I'm wondering if something else might be involved here...

**Comment by khalwat** [comment]
Will re-open if more information is provided.
