### ISSUE TITLE
makeMonacoEditor fails in Safari

### ISSUE THREAD

**Issue by spoeken** [nystudio107/craft-code-field#14]
### Describe the bug

The code editor does not work in Safari Version 16.2 (18614.3.7.1.5).
A plain texarea is displayed. 

Console errors:
```
[Error] SyntaxError: Invalid regular expression: invalid group specifier name
	(anonymous function) (vendors.js:11)
[Error] ReferenceError: Can't find variable: makeMonacoEditor
	Global Code (pellentesque-sit-amet:1392)
```

### To reproduce
1. Install and use the field on a page
2. Open the page in Safari, both the craft editing view and the entry page will give the error

### Expected behaviour
No console errors and syntax highlighted code

### Screenshots
<img width="688" alt="Screenshot 2024-03-07 at 16 30 25" src="https://github.com/nystudio107/craft-code-field/assets/1019016/93146427-4519-4194-bfdb-1965813a6fc7">
<img width="384" alt="Screenshot 2024-03-07 at 16 31 00" src="https://github.com/nystudio107/craft-code-field/assets/1019016/653e7334-8d3d-4a0b-b102-4d2814e90d24">

### Versions
- Plugin version: 4.0.12
- Craft version: 4.7.0

**Comment by spoeken** [comment]
Seems related to this: https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group

**Comment by spoeken** [comment]
And vs-code has a fix for it here I think, but its not in the monaco-editor repo?
https://github.com/microsoft/vscode/commit/95dee5b5baaf53e5bf31bd4213eda71a40982960

**Comment by spoeken** [comment]
This seems to be the actual issue: https://github.com/microsoft/monaco-editor/issues/4223

monaco-editor v0.43.0 might be the last working version
https://microsoft.github.io/monaco-editor/playground.html?source=v0.43.0#example-creating-the-editor-hello-world

**Comment by khalwat** [comment]
Looks like their answer is to update to Safari >= 16.3 and it will work again.

Given that we're on Safari 17.1 by now, I think we can safely close this.
