### ISSUE TITLE
[FR] - GraphQL access is not supported

### ISSUE THREAD

**Issue by aladrach** [nystudio107/craft-code-field#2]
### Describe the bug
We converted some one of our previous text fields, which was used in a Neo block. After converting and attempting to utilize the field's data via GraphQL, we receive the following error:
Error: String cannot represent value: instance of nystudio107\codefield\models\CodeData

### To reproduce
Steps to reproduce the behaviour:
1. Covert plain text field to Code field
2. Try to call field via GraphQL

### Versions
- Plugin version: 4.0.2
- Craft version: 4.3.1

**Comment by khalwat** [comment]
Ah yes, that makes sense. There's no type/resolver for it yet

**Comment by aladrach** [comment]
Ah, well that makes sense. Suppose this may be better suited for a feature request then haha.

**Comment by khalwat** [comment]
Implemented in

3.0.3 -> https://github.com/nystudio107/craft-code-field/releases/tag/3.0.3

4.0.3 -> https://github.com/nystudio107/craft-code-field/releases/tag/4.0.3

Docs updated to add a GraphQL example:

https://nystudio107.com/docs/code-field/#graphql

**Comment by khalwat** [comment]
If you have any issues, let me know @aladrach
