### ISSUE TITLE
[FR] - Allo changing of field storage type and length of data

### ISSUE THREAD

**Issue by alanski66** [nystudio107/craft-code-field#6]
What is the default storage type and size/length for this field in the db?

**Comment by khalwat** [comment]
`Schema::TYPE_TEXT`

https://github.com/nystudio107/craft-code-field/blob/develop-v3/src/fields/Code.php#L247

**Comment by alanski66** [comment]
If I need this to be medium text for extra length (which I do ) can I just change the schema and will it break updates?

**Comment by khalwat** [comment]
Just changing the schema should be fine -- but what I'll do is add an option to let people choose, just like text fields have.

**Comment by alanski66** [comment]
Fantastic - thank you

**Comment by khalwat** [comment]
Added in: https://github.com/nystudio107/craft-code-field/commit/3817d1265a73b05448519f8a5071ea6730dbba9a & https://github.com/nystudio107/craft-code-field/commit/928b0222fc855d75dd2b25afdd38857d53f0995d

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-code-field": "dev-develop-v3 as 3.0.8",
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-code-field": "dev-develop-v4 as 4.0.8",
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
Let me know how this works out for you @joomkit and I can cut a release.

**Comment by alanski66** [comment]
Craft 3:
 Problem 1
    - Root composer.json requires nystudio107/craft-code-field dev-develop as 3.0.8, found nystudio107/craft-code-field[dev-develop-v3, dev-develop-v4, 3.0.0, ..., v3.x-dev, 4.0.0, ..., v4.x-dev] but it does not match the constraint.

**Comment by khalwat** [comment]
Oh my bad sorry...

**Comment by khalwat** [comment]
It should look like this:

```
    "nystudio107/craft-code-field": "dev-develop-v3 as 3.0.8",
```

**Comment by alanski66** [comment]
NO worries  - cant see a 3.08 tag...

**Comment by khalwat** [comment]
yeah I just gave you the wrong branch name, see above

**Comment by alanski66** [comment]
Got it. Should I be seeing under advanced field settings default storage type selections? I have a (broken) link to monaco editorOptions  but thats about it

**Comment by khalwat** [comment]
Yes, it appears under Advanced. I also fixed that broken link.

Sounds like you don't have the new version pulled down, or some kind of caching is involved (opcache maybe?)

**Comment by khalwat** [comment]
Check the version in the `vendor/nystudio107/craft-code-field/composer.json`

**Comment by alanski66** [comment]
Yes it was the cache:) Seeing the column type selection now. Thanks for your support. Gonna test this on Craft 3 then do a migration to Craft 4 and test

**Comment by khalwat** [comment]
The only thing I'm unclear on is whether Craft will automatically change the column for you. I'm imagining it will, because my changes mirror how the Craft PlainText field works.
