### ISSUE TITLE
Line number gutter too thin

### ISSUE THREAD

**Issue by bencroker** [nystudio107/craft-code-field#8]
### Describe the bug

With line numbers enabled, the line number gutter is too thin and results in digits overlapping when the number is equal to or greater than 10.

### To reproduce
Steps to reproduce the behaviour:
1. Enable line numbers in the field settings.
2. Enter 10 lines of code or more.

### Expected behaviour
The gutter should adjust in width for line numbers.

### Screenshots

![Screenshot 2023-06-18 at 17 04 14](https://github.com/nystudio107/craft-code-field/assets/57572400/a68b58d3-8da2-43d3-8bda-4479703126aa)

### Versions
- Plugin version: 4.0.9
- Craft version: 4.4.14

**Comment by khalwat** [comment]
So this is unlikely to be a Craft Code Field thing, and more likely to be just a config setting for the Monaco Editor to give it the gutter space it needs.

**Comment by bencroker** [comment]
Right, should I have posted in https://github.com/nystudio107/craft-code-editor/issues?

**Comment by khalwat** [comment]
That would probably be closer, but what I'm saying is that it's probably a Monaco Editor thing. Probably just a config setting you need to tweak.

**Comment by bencroker** [comment]
Yes, it looks like you’re overriding the default `lineNumbersMinChars` value of `5` to `0`, possibly intentionally, at https://github.com/nystudio107/craft-code-editor/blob/1dfdde029997a5a547f5ab1698a3aa955fafff73/src/web/assets/src/js/default-monaco-options.ts#L16

Setting the value in the code editor field settings fixes the issue.

![Screenshot 2023-06-19 at 08 07 03](https://github.com/nystudio107/craft-code-field/assets/57572400/704899db-5d31-4c61-982f-d089dd4ace6d)

I wonder whether the default value should be changed, but that begs the question, to what? Maybe back to Monaco’s default value of `5`, which users can then override? That way, at least it doesn’t appear broken to begin with.

Or you could get really clever and count the number of lines and set the value of `lineNumbersMinChars` accordingly.

**Comment by khalwat** [comment]
Right, I provide some base settings by default so things look a nice as possible in most use cases. Remember it can be used as a single line code field as well.

The override settings are there for exactly this type of thing; if you want something other than the default.

By default, line numbers are off... and then the default `lineNumberMinChars` adds way too much space... but perhaps if they are on, it should not set a default (and use whatever Monaco wants to use)

**Comment by bencroker** [comment]
> By default, line numbers are off... and then the default `lineNumberMinChars` adds way too much space...

I believe this used to be the case, but it no longer is. In other words, `lineNumberMinChars` appears to be ignored if line numbers are off, so it seems safe to leave it to Monaco’s default value. See https://github.com/nystudio107/craft-code-editor/pull/3.

**Comment by khalwat** [comment]
Released as 1.0.10 -> https://github.com/nystudio107/craft-code-editor/releases/tag/1.0.10
