### ISSUE TITLE
Available Languages (Select "All") - Saving removes all selected languages

### ISSUE THREAD

**Issue by mmeintjes** [nystudio107/craft-code-field#9]
### Describe the bug
I added the code field to our content matrix (Type: Matrix) and every time I try and save the field with all code languages selected the field disregards all selected and saves the matrix field with none selected.

If I only add a few the field saves correctly and shows the dropdown to change the languages.

### To reproduce
Steps to reproduce the behaviour:
1. Add the codeField in a Matrix
2. Under "Available Languages" select "All"
3. Save the matrix field
4. Navigate to one of your entries and add the code field
5. There should be no drop down available
6. Navigate back to the settings and edit the matrix field
7. Under "Available Languages" everything is deselected.

### Expected behaviour
Selecting "All" should save correctly and show all the languages.

### Screenshots

![code_field_no_dropdown](https://github.com/nystudio107/craft-code-field/assets/103175403/2d21436e-bae3-4d89-bc8c-ab8678d70056)

![dropdown_none_selected](https://github.com/nystudio107/craft-code-field/assets/103175403/58fcc9a7-cf9c-48fc-9e32-004990d475b3)

![code_field_with_dropdown](https://github.com/nystudio107/craft-code-field/assets/103175403/ed2a8382-d311-4e0d-abe0-2cf8e35b0704)

### Versions
- Plugin version: 4.0.9
- Craft version: 4.4.14

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-code-field/commit/d6a31041a2f2aa33efbcb6026146e20c030c256a & https://github.com/nystudio107/craft-code-field/commit/59a2a269bdb1f5fd5f76e749aa8ffb7f0709a328

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-code-field": "dev-develop as 3.0.10”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-code-field": "dev-develop-v4 as 4.0.10”,
```
Then do a `composer clear-cache && composer update`
